version: '3.8'

services:

  db:
    image: postgres:latest
    container_name: online_store_db
    hostname: online_store_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: online_store
      POSTGRES_PASSWORD: 1234
      POSTGRES_SCHEMA: PUBLIC
    volumes:
      - ./Online-Store/src/main/resources/db/:/docker-entrypoint-initdb.d/
    ports:
      - "15432:5432"
    restart: always


  backend:
    build:
      context: .
      dockerfile: ./Online-Store/Dockerfile
    container_name: backend
    depends_on:
      - db
    ports:
      - "8080:8080"

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: frontend
    depends_on:
     - backend
    ports:
      - "8081:8081"
    restart: always