version: "3.9"


services:
  db:
    image: postgres:16.0
    container_name: db
    hostname: db
    environment:
      POSTGRES_DB: store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./src/main/resources/db/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    networks:
      myNetwork:


  backend:
    build: .
    container_name: backend
    depends_on:
      - db
    ports:
      - "8081:8080"
    networks:
      myNetwork:

networks:
  myNetwork: