version: "3.9"
services:
  db:
    image: postgres:latest
    container_name: online_store_db
    hostname: online_store_db
    environment:
      POSTGRES_DB: online_store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./src/main/resources/db/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  backend:
    build: .
    container_name: backend
    depends_on:
      - db
    ports:
      - "8081:8080"

#  frontend:
#    build: ./frontend
#    container_name: frontend
#    depends_on:
#      - backend
#    ports:
#      - "8081:8081"